### PR TITLE
chore(python): use isinstance for object type comparison

### PR DESCRIPTION
**Pull request by nullndr**
## Changelog

As [PEP8](https://peps.python.org/pep-0008/#programming-recommendations), you should use `isinstance` instead of `type(a) is B`.

### CODE REVIEW

**Comment by manast** [comment]
It seems like there is an issue with pytest as the github action seems to have been running for ever 🤔

**Comment by nullndr** [comment]
@manast is it possible to stop the test and get the logs?

**Comment by nullndr** [comment]
Sorry @manast, but the action seems to be stuck again

**Comment by manast** [comment]
Seems like after the third test it hangs for ever: https://github.com/taskforcesh/bullmq/actions/runs/4761883795/jobs/8463539900?pr=1825

**Pull request closed without merging**
