### PR TITLE
$ as default queue event id #76

### PR DESCRIPTION
**Pull request by jbr**
closes: #76

### CODE REVIEW

**Comment by manast** [comment]
thanks for the PR. Why can't you use ```waitUntilReady``` from the base class? seems like the effect will be the same.

**Comment by manast** [comment]
regarding consumer groups, I do not see how that would be useful in this case. Exactly once semantics is already provided by the current implementation, you just need to save the last event id and use it the next time you start listening to events.

**Comment by jbr** [comment]
@manast I was hesitant to use QueueBase#waitUntilReady because of this comment: https://github.com/taskforcesh/bullmq/blob/master/src/classes/queue-base.ts#L59. Will it make whatever refactor is going to be necessary on deprecation easier to use the same interface? What will waitUntilReady be replaced with on deprecation?

**Comment by jbr** [comment]
Updated to use QueueEvents#waitUntilReady

**Comment by manast** [comment]
@jbr if I recall correctly, the idea was to deprecate it as public method, and just use it internally when needed.

**Comment by jbr** [comment]
@manast As far as consumer groups (and [`XREADGROUP`](https://redis.io/commands/xreadgroup)), my read of the streams documentation suggested to me that the use of [`XACK`]( https://redis.io/commands/xack) would effectively mark an individual message as "done" for that consumer group, ensuring that it wouldn't be replayed. Storing the most recent id seems like it surfaces internal implementation details of the library in a way that most events users shouldn't _need_ to care about, and pushes the responsibility of storing ids in redis onto them.  If the preferred approach is to store the most recently processed event id instead of using consumer groups, it seems like _that_ behavior should be handled by bull internally

**Comment by manast** [comment]
@jbr consumer groups will not work for this use case since you want all the events to be delivered to all the workers.

**Comment by jbr** [comment]
@manast Is there more work needed on this PR? It uses waitUntilReady and $ and makes no other changes.

**Pull request merged**
