### PR TITLE
chore(python): replace staticmethod function with decorator

### PR DESCRIPTION
**Pull request by nullndr**
## Changelog

In python 3, the `staticmethod()` is a [decorator](https://docs.python.org/3/glossary.html#term-decorator).

### CODE REVIEW

**Comment by manast** [comment]
Nice. I am catching up a lot with the latest python developments thanks to your PRs.

**Comment by manast** [comment]
There seems to be an issue with the tests though: https://github.com/taskforcesh/bullmq/actions/runs/4697299452/jobs/8328226432?pr=1826#step:12:1

**Comment by nullndr** [comment]
@manast if you agree, I will continue this PR after I separated the types into a subfolder in order to break the circular dependencies

**Comment by nullndr** [comment]
@manast this PR is ready

**Pull request merged**
