### PR TITLE
Fix Error [ERR_REQUIRE_ESM]

### PR DESCRIPTION
**Pull request by AlexOwl**
Fix of the issue #1368

### CODE REVIEW

**Comment by manast** [comment]
Looks un-harmful but I have been biten several times with ESM support so I am not 100% this wont break somebody's deploy, need to be prepared to a revert if that happens.

**Comment by manast** [comment]
Reverted since as I suspected this is already creating errors on current users. This is my recommended approach that just works: https://blog.taskforce.sh/using-typescript-with-bullmq/

**Comment by AlexOwl** [comment]
I got the problem, better to check if current environment is ESM compatible then use import

**Comment by roggervalf** [comment]
hi @AlexOwl, it should be related to https://github.com/taskforcesh/bullmq/issues/917, please try version 1.89.1

**Pull request merged**
