### PR TITLE
Feat/support RRULE syntax for repeated jobs

### PR DESCRIPTION
**Pull request by emanuelet**
added support for [RRULE](https://datatracker.ietf.org/doc/html/rfc5545) notation to set-up repeated jobs schedule. 

RRULE is the de-facto standard when it comes to repeated calendar events, used by iCalendar and Google Calendar, and allows a much more granular and complex set of rules compared to cron.

The addition uses https://github.com/jakubroztocil/rrule to parse the string passed in the payload and generate the next job. 

ref https://github.com/taskforcesh/bullmq/issues/320

### CODE REVIEW

**Comment by manast** [comment]
Thank you for this fine PR. The implementation is fine, but I am trying to figure out if we could refactor a functionality like this as a separate plugin. There are basically two reasons for this 1) to avoid adding a new dependency, 2) to free us from more future maintenance burdens. I think a plugin mechanism for the Repeat functionality would not be very difficult to achieve considering it is mostly a matter of implementing the ```getNextMillis``` method in the repeat class. In fact, it may already be possible by subclassing Repeat. If we do this then we can link to the RRULE plugin on BullMQs main page.

**Comment by emanuelet** [comment]
so just so I understand what you are referring to, are you talking about doing something like this https://stackoverflow.com/a/26309279/3998747 ? or using this https://www.npmjs.com/package/patch-package ?

**Comment by manast** [comment]
@emanuelet no, I mean subclassing BullMQ classes. In this case, you probably need to subclass Queue and Repeat. You could have a QueueRRule and a RepeatRRule class, which just accept the RRULE options and implement a custom getNextMillis based on the RRULE. So similar to what you did but in a separate repo that you own.

**Comment by manast** [comment]
ah, and you also will need to subclass the Worker class, so that it uses the getNextMilllis method from the RepeatRRule class...
Maybe @roggervalf has more ideas on how to implement this smoothly.

**Comment by roggervalf** [comment]
I was thinking that maybe we can handle it like custom cronStrategies like in https://github.com/taskforcesh/bullmq/pull/1248

**Comment by emanuelet** [comment]
At the end of the day, I just wish to be able to pass RRULE strings to `bullmq` so I am happy either way

**Comment by roggervalf** [comment]
In favor of #1248

**Comment by emanuelet** [comment]
@roggervalf whats the status of #1248 ?

**Comment by roggervalf** [comment]
hey @emanuelet sorry for the delay, the feature is merged

**Comment by emanuelet** [comment]
thank you, much appreciated

**Pull request closed without merging**
