### PR TITLE
feat(python): add moveToDelayed script

### PR DESCRIPTION
**Pull request by roggervalf**

### CODE REVIEW

**Review by manast — COMMENTED** [review]
Looks good so far, but I see some out-commented code.

**Comment by roggervalf** [comment]
Yeah, I still need to add some tests too

**Comment by DanielNetzer** [comment]
@manast @roggervalf is this something usable?
We have a python service that can utilize a worker implementation for Python if so.

**Comment by manast** [comment]
@DanielNetzer the python lib uses the same lua scripts as the nodejs version, so apart from lacking some features, it should be quite safe to use in prod environments.

**Comment by DanielNetzer** [comment]
As always, thanks for the super fast response.  @manast 
Is it documented somewhere, the Python usage?

**Comment by manast** [comment]
https://docs.bullmq.io/python/introduction

**Comment by manast** [comment]
It is not a lot but hopefully enough. And the warning is 2 months ago, but still, it can be rough on the edges.

**Comment by DanielNetzer** [comment]
@manast this should be enough, again appreciate all the hard work invested in this library which is amazing.
We will start ASAP utilizing the python implementation and get back with feedback 👍🏽

**Pull request merged**
