### PR TITLE
fix(job): stack trace limit (#2487)

### PR DESCRIPTION
**Pull request by nocodehummel**
Changed the array slice for the stacktrace.

Resolution is verified with our BullMQ implementation (via npm link).

### CODE REVIEW

**Comment by manast** [comment]
What issue does this PR address?

**Comment by manast** [comment]
ok, I found it: https://github.com/taskforcesh/bullmq/issues/2487
We are going to need a small test to avoid a regression for this one.

**Comment by nocodehummel** [comment]
I adjusted the test scripts but do not have a local redis.

**Comment by nocodehummel** [comment]
I see that my test case failed because cannot `moveToFailed` when job is not active.

**Comment by nocodehummel** [comment]
> The change also affects a test case that is failing: https://github.com/taskforcesh/bullmq/actions/runs/8419326269/job/23056271205?pr=2488#step:7:950

That is the test case I extended with extra checks. I tried to use `moveToFailed` twice which causes the issue. Now I have retrieved the job again from the queue for the second `moveToFailed`. 

A bit frustrating to not have a local Redis. When this does not work. How can I run the test again a Cloud Redis?

**Comment by manast** [comment]
> A bit frustrating to not have a local Redis. When this does not work. How can I run the test with a Cloud Redis?

What is preventing you to running a local Redis instance? supports all OSes and also works on Docker.

**Comment by nocodehummel** [comment]
> > A bit frustrating to not have a local Redis. When this does not work. How can I run the test with a Cloud Redis?
> 
> What is preventing you from running a local Redis instance? supports all OSes and also works on Docker.

Test cases contain `const redisHost = process.env.REDIS_HOST || 'localhost';`, but I do not know how to set it.

**Comment by nocodehummel** [comment]
I managed to run the tests using `.env`, but now Chilld pool tests are failing. 
Do the test run when Redis host is configured as environment variable?

````
Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
````

**Comment by manast** [comment]
> Test cases contain `const redisHost = process.env.REDIS_HOST || 'localhost';`, but I do not know how to set it.

If you start a redis server locally then localhost points to that server, not sure I understand the issue...

**Comment by nocodehummel** [comment]
I managed to get the test case working and checking that the stacktrace actually changed.

````
> bullmq@5.4.5 test
> ts-mocha -p tsconfig-cjs.json --config ./.mocharc.js -r dotenv/config
  Job
    .moveToFailed
      ✔ applies stacktrace limit on failure (688ms)
  1 passing (975ms)
````

**Comment by nocodehummel** [comment]
> > Test cases contain `const redisHost = process.env.REDIS_HOST || 'localhost';`, but I do not know how to set it.
> 
> If you start a redis server locally then localhost points to that server, not sure I understand the issue...

The point is do not have a local Redis. It looks to me there is an issue with the test cases supporting a configured Redis host. People cannot always install anything they want on their PC.

**Pull request merged**
