### PR TITLE
fix(worker): consider removed jobs in failed event

### PR DESCRIPTION
**Pull request by roggervalf**
there is a test case that covers this case https://github.com/taskforcesh/bullmq/blob/master/tests/test_stalled_jobs.ts#L311-L377
ref https://github.com/taskforcesh/bullmq/issues/1495

### CODE REVIEW

**Comment by manast** [comment]
I wonder, do we know the underlying reason for the job to be undefined in this particular case? is it possible to fix it so that it always is sent?

**Comment by roggervalf** [comment]
it is undefined because it was removed when it was moved to failed as it has removeOnFailed as true

**Comment by manast** [comment]
Yes, that makes sense, that it is removed from Redis, but the worker itself should still keep a reference of the job instance, no?

**Comment by manast** [comment]
I mean, for the global failed event, yes it must be undefined, but is it really the case for the local worker event?

**Comment by roggervalf** [comment]
hey, the escenario where this is happening is when we have stalled jobs that were removed https://github.com/taskforcesh/bullmq/blob/master/src/classes/worker.ts#L790-L797 in that case the only value that is available is the jobId that is returned by stalled script, but as we are creating an instance of a Job with the id of the removed job, we ended with an undefined value

**Review by manast — APPROVED** [review]

**Pull request merged**
