### PR TITLE
chore(python): update python docs comments

### PR DESCRIPTION
**Pull request by nullndr**
## Changelog

This PR updates all python docs comments to match the ones in the node version.

I had to format these files with the formatter in my vscode, but it should be the standard, so some lines have changed for this, for example a line has been added between two functions since by standard this should be the default formatting rule.

### CODE REVIEW

**Comment by manast** [comment]
Which formatter are you using?

**Review by manast — APPROVED** [review]

**Comment by nullndr** [comment]
In visual studio code, the [official extension for Python](https://marketplace.visualstudio.com/items?itemName=ms-python.python) by Microsoft.

**Comment by nullndr** [comment]
Hey @manast, is there something that block this PR to be merged? Do you have other questions or suggestions with the formatter?

**Comment by manast** [comment]
Very nice, thanks.

**Pull request merged**
