### PR TITLE
feat(telemetry): add option to omit context propagation

### PR DESCRIPTION
**Pull request by fgozdz**
ref #2942

### CODE REVIEW

**Comment by roggervalf** [comment]
Wondering if an extra option can be passed at job level as for the case that was reportes, only repeatables jobs in some cases need this logic but we can keep the base logic for all the other job types

**Comment by fgozdz** [comment]
I have changed it to pass the option entirely in bullmq, inside the job. For now only in methods regarding enhancement issue.

**Review by fgozdz — COMMENTED** [review]
LGTM

**Review by manast — APPROVED** [review]

**Comment by manast** [comment]
I will squash this PR as there were a few commits on this one...

**Pull request merged**
