### PR TITLE
feat(scheduler): add getJobScheduler method

### PR DESCRIPTION
**Pull request by roggervalf**
ref https://github.com/taskforcesh/bullmq/issues/2875

### CODE REVIEW

**Comment by lpoulin** [comment]
@roggervalf is it planned to store the jobTemplate on the jobScheduler object at some point?

**Comment by roggervalf** [comment]
this is something that was talked about few weeks ago with my team. I'll revive that conversation

**Comment by lpoulin** [comment]
thanks @roggervalf! please let me know if I can provide any more details about my use-case.

**Review by manast — APPROVED** [review]
LGTM

**Pull request merged**
