### PR TITLE
perf: remove old marker logic

### PR DESCRIPTION
**Pull request by roggervalf**
No need to support old marker logic removal as markers are living in a different key now in recent versions
Also we should validate if a jobId contains : as this separator could break flow logic https://github.com/taskforcesh/bullmq/blob/c60e6a3f45606c623ef6a2b16415d67eac9b0269/src/classes/flow-producer.ts#L419

### CODE REVIEW

**Comment by manast** [comment]
What would be the proper way to migrate from a version older than v5 to v6? for instance, if we upgrade from v4, then to v5 and then to v6, there could still be markers left, and break the queue.

**Comment by roggervalf** [comment]
> What would be the proper way to migrate from a version older than v5 to v6? for instance, if we upgrade from v4, then to v5 and then to v6, there could still be markers left, and break the queue.

I added a method to remove legacy markers in case someone come from an older version

**Comment by manast** [comment]
> 
> I added a method to remove legacy markers in case someone come from an older version

I think we also need a code example on how to do the migration. For instance, when should this method be called, and also is there a risk that the queue gets stuck before calling it? maybe we need to do a pause/remove markers/resume cycle or something like this.

**Comment by roggervalf** [comment]
> > I added a method to remove legacy markers in case someone come from an older version
> 
> I think we also need a code example on how to do the migration. For instance, when should this method be called, and also is there a risk that the queue gets stuck before calling it? maybe we need to do a pause/remove markers/resume cycle or something like this.

code example could be added in migration guide similar to what was done in previous breaking changes like https://bullmq.io/news/062123/faster-priority-jobs/ where removeDeprecatedPriorityKey was mentioned. This method is similar as it's also intended to be used one time. I also added a test case to demonstrate that queues won't get stuck and having queues in a paused state will be the best option to not process that legacy marker as a regular job.

**Review by manast — APPROVED** [review]
LGTM

**Pull request merged**
