### PR TITLE
feat: Retrieve Jobs by ID pattern

### PR DESCRIPTION
**Pull request by Skn0tt**
I'm using bullmq for [Quirrel](https://quirrel.dev) and need a way to fetch pending jobs. This PR adds a new function `getJobByIdPattern` that can be used like the following:

```ts
const { newCursor, jobs: jobsByCustomer1 } = await queue.getJobByIdPattern("customer1:*")

// later on ...

const { jobs: nextBatchOfJobsByCustomer1 } = await queue.getJobByIdPattern("customer1:*", newCursor)
```

### CODE REVIEW

**Comment by manast** [comment]
thanks for a very good written patch.
A couple of comments: 
I am wondering if you could share the complete use case for this, when you write pending jobs I am not sure what you mean. Studying the code, it will return all jobs matching the pattern even jobs that have been completed, failed or active, not just delayed and waiting, which would be what I would intuitively understand for "pending".
Secondly, it may be important to consider performance here, in a redis instance with many queues it could be slow to iterate across all job keys, also consider that the scan command can return zero keys if it does not match any keys in one iteration.
Thirdly, it would be great with some documentation for this new feature too :).

**Comment by Skn0tt** [comment]
Thanks for the quick response :)

**About the use case:**
Quirrel is a managed task queue for serverless deployments. In its current implementation, it's basically a HTTP adapter to `bullmq`.
- `POST /jobs` adds a new job
- `DELETE /jobs/:id` can be used to prevent delayed jobs from executing.

Every job is given an ID that adheres to the following schema: `<customer>:<queue>:<job-id>`. 

I now want to add a new route `GET /jobs` that retrieves all delayed jobs that haven't been executed. It uses `getJobFromIdPattern('<customer>:*:*', ...)` to achieve that. Since I enabled `removeOnComplete`, this works for my use case.

**About performance:**

The [Redis docs on `SCAN`](https://redis.io/commands/scan) call it production-safe, so I don't think that should be a problem.

About matching jobs during one iteration: What do you propose to do about this? We could add another set that contains the IDs of a queue's jobs, but that'd come with increased complexity.

**About docs:**

Will do ^^

**Comment by manast** [comment]
hmm, ok, lets see, do you mean you want to get all the jobs from a given customer, across all his queues?

**Comment by Skn0tt** [comment]
I have one big queue that contains all of the jobs, rather than one per customer. If I had one per customer, there'd be a lot of idle Redis connections, which I don't want.

Individual customers are distinguished by the unique IDs their jobs receive: `<customer>:<queue>:<custom-job-id>`.

When a customer makes a call (say `GET /jobs/my-queue`), I scan across all delayed jobs for that customer x queue: `randomcustomer:my-queue:*`.

**Comment by Skn0tt** [comment]
I've added a new method `.getJobsByName` that returns all jobs with a specific name. To make this more performant, I added a new `SET` called `by-name:<job-name>`, containing the IDs of all jobs with a specific name. This can then be `SSCAN`ed easily. It's updated in the `addJob` and `removeJob` commands.

As you rightfully demanded, I've also added docs.

**Comment by nemphys** [comment]
Any news on this? Would be a very nice feature.

**Comment by Skn0tt** [comment]
I don't need this feature anymore, resorted to writing [my own queueing library](https://github.com/quirrel-dev/owl) at some point. But still, this would be a very nice feature indeed!

**Comment by manast** [comment]
This is a fine PR but the reason I have not merged it is because it creates a new data set which many users will not need, so I have been reluctant to merge it. Also, I think this could be refactored into a separate module that works side-by-side with Bullmq so that we do not need to increase the size of the core module.

**Comment by Skn0tt** [comment]
That sounds sensible. I won't be able to write that 3rd party module since I don't use BullMQ anymore (see above) - but if anybody wants to do that, go ahead and grab this PR's code :D

**Comment by nemphys** [comment]
Wouldn't it be nice if the new feature was optional through a parameter (and disabled by default, so that it does not affect users that don't need it)?
It would be a shame for this to be left out like this.

**Comment by manast** [comment]
@nemphys if somebody wants to pick up on this job and implement it as an optional feature then there are good chances it will be merged.

**Pull request closed without merging**
